version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: riverside_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studiocast
    ports:
      - "5454:5432"  # Host:Container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
